### ISSUE TITLE
remote_test: checkchecking a dead player

### ISSUE THREAD

**Issue by ArchieT** [ArchieT/3manchess#23]
```
2016/04/04 00:53:31 now MoveIt {[1,1] [2,3] Board:  [
[__ __ .B .Q .K .B __ .R __ __ .♗ __ .♔ .♗ __ .♖ __ .n .b .q .k .b __ .r]
[__ .n .P .P .P .P .P .P __ .♙ .♙ .♙ .♙ .♙ .♙ .♙ __ .p .p .p .p .p .p .p]
[__ __ __ __ __ __ __ __ .♕ __ __ __ __ .♘ __ __ __ __ __ __ __ __ __ __]
[.P __ .N __ __ __ __ .N .♙ __ __ __ __ __ __ __ .p __ __ __ __ __ __ __]
[__ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __]
[__ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __]]
[false false false] Black [[true false]X[true false]X[true false]]X[[127,127]X[127,127]] 1 27 [true true true]
 0}

2016/04/04 00:53:31 MoveIT returned Board:  [
[__ __ .B .Q .K .B __ .R __ __ .♗ __ .♔ .♗ __ .♖ __ .n .b .q .k .b __ .r]
[__ __ .P .P .P .P .P .P __ .♙ .♙ .♙ .♙ .♙ .♙ .♙ __ .p .p .p .p .p .p .p]
[__ __ __ .n __ __ __ __ .♕ __ __ __ __ .♘ __ __ __ __ __ __ __ __ __ __]
[.P __ .N __ __ __ __ .N .♙ __ __ __ __ __ __ __ .p __ __ __ __ __ __ __]
[__ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __]
[__ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __]]
[false false false] Gray [[true false]X[true false]X[true false]]X[[127,127]X[127,127]] 2 28 [false true true]
```

```
 mf  ⋯  3manchess  client  remote   statejson  go test -v
=== RUN   TestNew_ai3
panic: CheckChecking a dead player!: White

goroutine 26240 [running]:
panic(0x72b6c0, 0xc8205c0610)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/ArchieT/3manchess/game.(*Board).CheckChecking(0xc8202a4fc0, 0xc801010001, 0x106c820000000)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/move.go:169 +0x107
github.com/ArchieT/3manchess/game.(*State).AmIInCheck(0xc82000a660, 0xc8202a4f01, 0xc820000000)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/endgame.go:42 +0x4b
github.com/ArchieT/3manchess/game.(*Move).After(0xc8201a3da8, 0xc800040003, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/move.go:428 +0x6e8
github.com/ArchieT/3manchess/game.(*State).CanIMoveWOCheck(0xc82000a640, 0xc8200ee001, 0xc8200ed440)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/endgame.go:17 +0x161
github.com/ArchieT/3manchess/game.(*State).EvalDeath(0xc82000a640)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/state.go:224 +0x2e
github.com/ArchieT/3manchess/game.(*Move).EvalAfter(0xc8201a3f18, 0xc82000a640, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/move.go:438 +0x5c
github.com/ArchieT/3manchess/game.ASAOMGen.func1(0xc82000a400, 0xc820519902, 0xc8200ee000)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/asaomgen.go:14 +0x2ab
created by github.com/ArchieT/3manchess/game.ASAOMGen
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/asaomgen.go:27 +0x66
exit status 2
FAIL	github.com/ArchieT/3manchess/client/remote	250.947s
```

```
2016/04/04 00:53:31 {0xc208012a80 0xc2081ff510} <nil>
2016/04/04 00:53:31 75 <nil>
2016/04/04 00:53:31 {101 129} <nil>
2016/04/04 00:53:31 POST        /api/play/128   APITurn 91.912ms
2016/04/04 00:53:31 GET /api/move/101   APIMove 364µs
2016/04/04 00:53:31 GET /api/play/129   APIPlay 493µs
2016/04/04 00:53:31 GET /api/state/75   APIState        2.536ms
2016/04/04 00:53:31 GET /api/play/129/after     APIAfter        584µs
2016/04/04 00:53:32 GET /api/play/128/after     APIAfter        464µs
2016/04/04 00:53:32 GET /api/move/101   APIMove 232µs
2016/04/04 00:53:32 GET /api/play/129   APIPlay 306µs
2016/04/04 00:53:32 GET /api/state/75   APIState        1.365ms
```

everything available on platinum instance (as of 2016-04-04 01:05 GMT+2)

**Comment by ArchieT** [comment]
```
 mf  ~  2  chessrunbot -gray -botid 1 -gameid 156 -login remotetest -passwd remotetest
2016/04/06 07:45:34 1 [56 48 98 49 56 101 53 99 52 52 99 54 49 56 56 102 53 99 53 49 50 55 57 100 98 98 99 52 55 54 51 99]
2016/04/06 07:45:34 botid 1
2016/04/06 07:45:34 &{[99 111 110 115 116 115 105 116 118 97 108 45 100 101 109 111 116 101 115 116] 1 bot0 2 [123 34 68 101 112 116 104 34 58 48 44 34 79 119 110 101 100 84 111 84 104 114 101 97 116 101 110 101 100 34 58 52 125]}
2016/04/06 07:45:34 &{0xc8200caa40 156 0xc8200e4560 0xc820010f40 2 {2 [99 97 102 102 54 56 56 97 98 56 97 101 57 50 49 97 55 54 49 102 54 101 100 56 52 50 101 98 56 57 49 100]} 0xc820018de0 0x402f40}
panic: CheckChecking a dead player!: White

goroutine 34 [running]:
panic(0x6e7900, 0xc8201485f0)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/ArchieT/3manchess/game.(*Board).CheckChecking(0xc820144b40, 0xc801010001, 0x106c820000000)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/move.go:169 +0x107
github.com/ArchieT/3manchess/game.(*State).AmIInCheck(0xc8201420a0, 0xc820144b01, 0xc820000000)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/endgame.go:42 +0x4b
github.com/ArchieT/3manchess/game.(*Move).After(0xc82015fda8, 0xc800040003, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/move.go:428 +0x6e8
github.com/ArchieT/3manchess/game.(*State).CanIMoveWOCheck(0xc820142080, 0xc82014a001, 0xc820156000)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/endgame.go:17 +0x161
github.com/ArchieT/3manchess/game.(*State).EvalDeath(0xc820142080)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/state.go:224 +0x2e
github.com/ArchieT/3manchess/game.(*Move).EvalAfter(0xc82015ff18, 0xc820142080, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/move.go:438 +0x5c
github.com/ArchieT/3manchess/game.ASAOMGen.func1(0xc820142000, 0xc820040902, 0xc82014a000)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/asaomgen.go:14 +0x2ab
created by github.com/ArchieT/3manchess/game.ASAOMGen
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/asaomgen.go:27 +0x66
 mf  ~  2  
```

**Comment by ArchieT** [comment]
Solved in d23afa4, tested in 1547185 ?

**Comment by ArchieT** [comment]
@Subc2

**Comment by Subc2** [comment]
Yes, d23afa4c2a55b0c73a2b0bdf04039ce40466f6c1 is necessary and fixes this bug.
