### ISSUE TITLE
panic: index out of range on gameid:1480 and 1517

### ISSUE THREAD

**Issue by ArchieT** [ArchieT/3manchess#34]
```
 mf  ⋯  3manchess  cmd  chessrunbot   master  chessrunbot -botid 2 -login remotetest -passwd remotetest  -color 2 -gameid 1480
2016/04/08 23:53:37 2
2016/04/08 23:53:37 Gray
2016/04/08 23:53:37 1 [56 48 98 49 56 101 53 99 52 52 99 54 49 56 56 102 53 99 53 49 50 55 57 100 98 98 99 52 55 54 51 99]
2016/04/08 23:53:37 botid 2
2016/04/08 23:53:37 &{[99 111 110 115 116 115 105 116 118 97 108 45 100 101 109 111 116 101 115 116] 1 bot1 3 [123 34 68 101 112 116 104 34 58 48 44 34 79 119 110 101 100 84 111 84 104 114 101 97 116 101 110 101 100 34 58 53 125]}
2016/04/08 23:53:37 Gray
2016/04/08 23:53:37 &{0xc8200c0a60 1480 0xc820104680 0xc8200f62c0 2 {3 [98 55 97 50 100 50 52 55 56 101 51 55 99 50 97 102 51 102 51 50 48 97 97 54 54 98 48 101 98 57 100 48]} 0xc820140480 0x4033f0}
panic: runtime error: index out of range

goroutine 21 [running]:
panic(0x787c80, 0xc82000e100)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/ArchieT/3manchess/game.(*Board).diagonal(0xc820510480, 0x3050c04, 0xc8204dc100)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/possibilities.go:188 +0x966
github.com/ArchieT/3manchess/game.(*Board).queen(0xc820510480, 0x7f00000003050c04, 0x101010000000000)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/possibilities.go:470 +0xbb
github.com/ArchieT/3manchess/game.(*Board).AnyPiece(0xc820510480, 0x3050c04, 0x7f7f7f0000000000, 0xc80101017f, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/possibilities.go:507 +0x386
github.com/ArchieT/3manchess/game.(*Board).WeAreThreatened(0xc820510480, 0x7f7f7f7f01010101, 0xc8204e6180)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/move.go:244 +0x3d7
github.com/ArchieT/3manchess/ai/constsitval.(*AIPlayer).SitValue(0xc8200f62c0, 0xc8200c0ae0, 0x25)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/ai/constsitval/values.go:24 +0x15c
github.com/ArchieT/3manchess/ai/constsitval.(*AIPlayer).Worker(0xc8200f62c0, 0xc8200f2ea0, 0x2, 0x0, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/ai/constsitval/ai.go:93 +0x245
github.com/ArchieT/3manchess/ai/constsitval.(*AIPlayer).Think(0xc8200f62c0, 0xc820104680, 0xc820140540, 0xc800000000, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/ai/constsitval/ai.go:144 +0x49b
github.com/ArchieT/3manchess/ai/constsitval.(*AIPlayer).HeyItsYourMove(0xc8200f62c0, 0xc820104680, 0xc820140540, 0x0, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/ai/constsitval/ai.go:154 +0x54
github.com/ArchieT/3manchess/client/remote.(*G).askplayer(0xc820140420, 0x0, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/client/remote/remote.go:68 +0xe7
github.com/ArchieT/3manchess/client/remote.(*G).(github.com/ArchieT/3manchess/client/remote.askplayer)-fm(0x0, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/client/remote/remote.go:146 +0x46
github.com/ArchieT/3manchess/client/remote.(*G).Turn(0xc820140420, 0x0, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/client/remote/remote.go:150 +0xab
github.com/ArchieT/3manchess/client/remote.(*G).Procedure(0xc820140420, 0xc8201401e0, 0xc820140180)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/client/remote/remote.go:161 +0x7e
created by github.com/ArchieT/3manchess/client/remote.New
	/home/mf/gopath/src/github.com/ArchieT/3manchess/client/remote/remote.go:61 +0x298
 mf  ⋯  3manchess  cmd  chessrunbot   master  2  
```

**Comment by ArchieT** [comment]
```
 mf  ⋯  3manchess  cmd  chessrunbot   master  130  chessrunbot -botid 2 -login remotetest -passwd remotetest -gameid 1517 -color 3
2016/04/10 06:05:10 3
2016/04/10 06:05:10 Black
2016/04/10 06:05:10 1 [56 48 98 49 56 101 53 99 52 52 99 54 49 56 56 102 53 99 53 49 50 55 57 100 98 98 99 52 55 54 51 99]
2016/04/10 06:05:10 botid 2
2016/04/10 06:05:10 &{[99 111 110 115 116 115 105 116 118 97 108 45 100 101 109 111 116 101 115 116] 1 bot1 3 [123 34 68 101 112 116 104 34 58 48 44 34 79 119 110 101 100 84 111 84 104 114 101 97 116 101 110 101 100 34 58 53 125]}
2016/04/10 06:05:10 Black
2016/04/10 06:05:10 &{0xc8200c8a60 1517 0xc8200fa4e0 0xc820110340 3 {3 [98 55 97 50 100 50 52 55 56 101 51 55 99 50 97 102 51 102 51 50 48 97 97 54 54 98 48 101 98 57 100 48]} 0xc8201285a0 0x4033f0}
panic: runtime error: index out of range

goroutine 26 [running]:
panic(0x788180, 0xc82000e100)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/ArchieT/3manchess/game.(*Move).After(0xc820167da8, 0x0, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/move.go:343 +0x138a
github.com/ArchieT/3manchess/game.(*State).CanIMoveWOCheck(0xc8200fbdc0, 0x452003, 0xc820128780)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/endgame.go:13 +0xfc
github.com/ArchieT/3manchess/game.(*State).EvalDeath(0xc8200fbdc0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/state.go:224 +0x2e
github.com/ArchieT/3manchess/game.(*Move).EvalAfter(0xc820167f30, 0xc8200fbdc0, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/move.go:440 +0x6a
github.com/ArchieT/3manchess/game.ASAOMGen.func1(0xc82010c7e0, 0xc820164903, 0xc820128780)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/asaomgen.go:20 +0x518
created by github.com/ArchieT/3manchess/game.ASAOMGen
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/asaomgen.go:27 +0x66
 mf  ⋯  3manchess  cmd  chessrunbot   master  2  
```

**Comment by Subc2** [comment]
Solved in e0228f7de3983ef9d2a4c24eb27248afe1bd08a6, tested in 02ffd26f173d3dc48999fb5688e06add213b226c.

**Comment by ArchieT** [comment]
```
 mf  ⋯  3manchess  cmd  chessrunbot   master  chessrunbot -botid 2 -login remotetest -passwd remotetest -gameid 1619 -color 3
2016/04/12 23:28:39 3
2016/04/12 23:28:39 Black
2016/04/12 23:28:39 1 [56 48 98 49 56 101 53 99 52 52 99 54 49 56 56 102 53 99 53 49 50 55 57 100 98 98 99 52 55 54 51 99]
2016/04/12 23:28:39 botid 2
2016/04/12 23:28:39 &{[99 111 110 115 116 115 105 116 118 97 108 45 100 101 109 111 116 101 115 116] 1 bot1 3 [123 34 68 101 112 116 104 34 58 48 44 34 79 119 110 101 100 84 111 84 104 114 101 97 116 101 110 101 100 34 58 53 125]}
2016/04/12 23:28:39 Black
2016/04/12 23:28:39 &{0xc8200d4ae0 1619 0xc8201264e0 0xc8200f4400 3 {3 [98 55 97 50 100 50 52 55 56 101 51 55 99 50 97 102 51 102 51 50 48 97 97 54 54 98 48 101 98 57 100 48]} 0xc8200f6600 0x4033f0}
panic: runtime error: index out of range

goroutine 563 [running]:
panic(0x788360, 0xc82000e100)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/ArchieT/3manchess/game.(*Move).After(0xc8204add18, 0x0, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/move.go:414 +0x2284
github.com/ArchieT/3manchess/game.(*State).CanIMoveWOCheck(0xc820107ea0, 0xc8205c4003, 0xc8204b0801)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/endgame.go:11 +0x1e2
github.com/ArchieT/3manchess/game.(*State).EvalDeath(0xc820107ea0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/state.go:224 +0x56
github.com/ArchieT/3manchess/game.(*Move).EvalAfter(0xc8204adf30, 0xc820107ea0, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/move.go:429 +0x6a
github.com/ArchieT/3manchess/game.ASAOMGen.func1(0xc820127500, 0xc82004f903, 0xc8205c4000)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/asaomgen.go:20 +0x518
created by github.com/ArchieT/3manchess/game.ASAOMGen
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/asaomgen.go:27 +0x66
 mf  ⋯  3manchess  cmd  chessrunbot   master  2  
```

**Comment by ArchieT** [comment]
```
 mf  ⋯  3manchess  cmd  chessrunbot   master  2  chessrunbot -login remotetest -passwd remotetest -botid 1 -color 1 -gameid 1637
2016/04/12 23:36:39 1
2016/04/12 23:36:39 White
2016/04/12 23:36:39 1 [56 48 98 49 56 101 53 99 52 52 99 54 49 56 56 102 53 99 53 49 50 55 57 100 98 98 99 52 55 54 51 99]
2016/04/12 23:36:39 botid 1
2016/04/12 23:36:39 &{[99 111 110 115 116 115 105 116 118 97 108 45 100 101 109 111 116 101 115 116] 1 bot0 2 [123 34 68 101 112 116 104 34 58 48 44 34 79 119 110 101 100 84 111 84 104 114 101 97 116 101 110 101 100 34 58 52 125]}
2016/04/12 23:36:39 White
2016/04/12 23:36:39 &{0xc8200c8ae0 1637 0xc8200f84e0 0xc82010e340 1 {2 [99 97 102 102 54 56 56 97 98 56 97 101 57 50 49 97 55 54 49 102 54 101 100 56 52 50 101 98 56 57 49 100]} 0xc8201265a0 0x4033f0}
panic: runtime error: index out of range

goroutine 28 [running]:
panic(0x788360, 0xc82000e100)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/ArchieT/3manchess/game.(*Move).After(0xc82015eef0, 0x0, 0x0, 0x0)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/move.go:365 +0x1874
github.com/ArchieT/3manchess/game.VFTPGen.func1(0xc82010a860, 0xc820126840)
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/vftpgen.go:13 +0x1f4
created by github.com/ArchieT/3manchess/game.VFTPGen
	/home/mf/gopath/src/github.com/ArchieT/3manchess/game/vftpgen.go:27 +0x5d
 mf  ⋯  3manchess  cmd  chessrunbot   master  2  
```
