### ISSUE TITLE
Server crashes on checkmate (play/64287) (BEWARE! It CRASHES! (and I have to relaunch it!)

### ISSUE THREAD

**Issue by ArchieT** [ArchieT/3manchess#38]
```
$ trychessserver -u archiet -p ******* -d archiet

2016/04/23 07:33:51 0xc208000870 0xc2080009f0 0xc208000a50
2016/04/23 07:33:51 <nil>
2016/04/23 07:33:55 GET /api/play/64287 APIPlay 1.307ms
2016/04/23 07:33:55 GET /api/state/64287        APIState        2.171ms
panic: CheckChecking a dead player!: Black

goroutine 23 [running]:
github_com_ArchieT_3manchess_game.CheckChecking.pN39_github_com_ArchieT_3manchess_game.Board
        /home/archiet/gopath/src/github.com/ArchieT/3manchess/game/move.go:162
github_com_ArchieT_3manchess_game.AmIInCheck.pN39_github_com_ArchieT_3manchess_game.State
        /home/archiet/gopath/src/github.com/ArchieT/3manchess/game/endgame.go:33
github_com_ArchieT_3manchess_game.After.pN38_github_com_ArchieT_3manchess_game.Move
        /home/archiet/gopath/src/github.com/ArchieT/3manchess/game/move.go:415
game.$nested1
        /home/archiet/gopath/src/github.com/ArchieT/3manchess/game/vftpgen.go:13
created by github_com_ArchieT_3manchess_game.VFTPGen
        /home/archiet/gopath/src/github.com/ArchieT/3manchess/game/vftpgen.go:8

goroutine 16 [IO wait]:
github_com_ArchieT_3manchess_multi.Run.pN40_github_com_ArchieT_3manchess_multi.Multi
        /home/archiet/gopath/src/github.com/ArchieT/3manchess/multi/multiweb.go:27
main.main
        /home/archiet/gopath/src/github.com/ArchieT/3manchess/cmd/trychessserver/main.go:23

goroutine 18 [finalizer wait]:

goroutine 20 [chan receive]:

goroutine 21 [IO wait]:

goroutine 22 [chan receive]:
github_com_ArchieT_3manchess_multi.APIVFTPGen.pN40_github_com_ArchieT_3manchess_multi.Multi
        /home/archiet/gopath/src/github.com/ArchieT/3manchess/multi/multiweb.go:459
multi.$nested0
        /home/archiet/gopath/src/github.com/ArchieT/3manchess/multi/multiweb.go:40
github_com_gorilla_mux.ServeHTTP.pN29_github_com_gorilla_mux.Router
        /home/archiet/gopath/src/github.com/gorilla/mux/mux.go:103
 platinum  archiet  ⋯  3manchess  cmd  trychessserver   master  2 

```

**Comment by ArchieT** [comment]
b523d89f34b07f9f6efa721f7dbfad2c0685b1f4 FIXED!!!! :smiley:

**Comment by ArchieT** [comment]
Damn. Still crashed, I've only tested move_test, and not the server itself.

**Comment by ArchieT** [comment]
Gotta delete that gameplay.
